# Generated by Django 4.0.6 on 2022-09-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catgirls', '0002_alter_catgirl_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catgirl',
            name='photo',
            field=models.ImageField(null=True, unique=True, upload_to='photos/', verbose_name='Внешний вид'),
        ),
    ]
